import os
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

path_1 = os.path.dirname(__file__) + r"\assets\frame0"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(path_1)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("338x358")
window.configure(bg = "#002849")


canvas = Canvas(
    window,
    bg = "#002849",
    height = 358,
    width = 338,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    71.69696044921875,
    7.3160400390625,
    anchor="nw",
    text="{NAME}",
    fill="#FFFFFF",
    font=("Staatliches Regular", 70 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=174.1212158203125,
    y=251.67098999023438,
    width=86.3290023803711,
    height=86.3290023803711
)

canvas.create_text(
    108.27703857421875,
    166.80514526367188,
    anchor="nw",
    text="00,00",
    fill="#FFFFFF",
    font=("Staatliches Regular", 52 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=67.307373046875,
    y=257.5237731933594,
    width=80.47618865966797,
    height=80.47618865966797
)

canvas.create_rectangle(
    11.70562744140625,
    80.47616577148438,
    466.76190185546875,
    567.722900390625,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    164.51947021484375,
    126.47616577148438,
    image=image_image_1
)

canvas.create_rectangle(
    -1.4632034301757812,
    239.9653549194336,
    338.0000108183449,
    242.8917618576014,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
