import os
import subprocess
import sys
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

from DatabaseFunctions import User

path_1 = os.path.dirname(__file__) + r"\assets\frame0"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(path_1)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


email = sys.argv[1]


def changePassword():
    password_1 = entry_1.get()
    password_2 = entry_2.get()
    user = User(email)
    if password_1 == password_2:
        user.password = password_1
        messagebox.showinfo("Password Changed", "Your password changed successfully.")
        next_page_path = os.path.dirname(__file__)
        next_page_path = next_page_path.replace(r"gui\newpassword\build", "")
        next_page_path = next_page_path + r"gui\sign in\build\SignIn.py"
        print(next_page_path)
        subprocess.Popen([sys.executable, next_page_path])
    else:
        messagebox.showerror("Wrong code", "The code entered is not the same code, Please enter the same code.")


window = Tk()

window.geometry("413x281")
window.configure(bg="#002849")

canvas = Canvas(
    window,
    bg="#002849",
    height=281,
    width=413,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    60.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: changePassword(),
    relief="flat"
)
button_1.place(
    x=11.0,
    y=252.0,
    width=378.0,
    height=23.783782958984375
)

canvas.create_rectangle(
    8.0,
    143.0,
    401.0,
    143.0000343571512,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    8.0,
    245.99996948242188,
    401.0,
    246.00000383957308,
    fill="#000000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    211.5,
    178.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=39.0,
    y=162.0,
    width=345.0,
    height=30.0
)

canvas.create_rectangle(
    11.0,
    162.0,
    39.0,
    194.0,
    fill="#235786",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    25.0,
    178.0,
    image=image_image_2
)

canvas.create_text(
    8.0,
    121.0,
    anchor="nw",
    text="reset your password",
    fill="#000000",
    font=("Staatliches Regular", 20 * -1)
)

canvas.create_text(
    11.0,
    147.0,
    anchor="nw",
    text="enter new password",
    fill="#000000",
    font=("Staatliches Regular", 12 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    211.5,
    225.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=39.0,
    y=209.0,
    width=345.0,
    height=30.0
)

canvas.create_rectangle(
    11.0,
    209.0,
    39.0,
    241.0,
    fill="#235786",
    outline="")

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    25.0,
    225.0,
    image=image_image_3
)

canvas.create_text(
    11.0,
    194.0,
    anchor="nw",
    text="reenter new password",
    fill="#000000",
    font=("Staatliches Regular", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
