import os
import subprocess
import sys
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

from DatabaseFunctions import User
from SendEmail import sendMail

path_1 = os.path.dirname(__file__) + r"\assets\frame0"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(path_1)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def SendEmaill():
    currentEmail = entry_1.get()
    path_1 = os.path.dirname(__file__)
    path_1 = path_1.replace(r"gui\forgot password\build", "")
    path_1 = path_1 + r"gui\code_for_reset\build\CodeReset.py"
    user = User(currentEmail)

    if sendMail(user):
        subprocess.Popen([sys.executable, path_1, currentEmail,"reset"])

    else:
        messagebox.showerror("Invalid Email", "The email entered is not valid. Please enter a valid email address.")


window = Tk()

window.geometry("413x258")
window.configure(bg="#002849")

canvas = Canvas(
    window,
    bg="#002849",
    height=258,
    width=413,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    60.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: SendEmaill(),
    relief="flat"
)
button_1.place(
    x=11.0,
    y=216.0,
    width=378.0,
    height=23.783782958984375
)

canvas.create_rectangle(
    5.0,
    153.0,
    398.0,
    153.0000343571512,
    fill="#000000",
    outline="")

canvas.create_text(
    11.0,
    156.0,
    anchor="nw",
    text="Email",
    fill="#FFFDFD",
    font=("Staatliches Regular", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    211.5,
    187.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=39.0,
    y=171.0,
    width=345.0,
    height=30.0
)

canvas.create_rectangle(
    11.0,
    171.0,
    39.0,
    203.0,
    fill="#235786",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    25.0,
    187.0,
    image=image_image_2
)

canvas.create_text(
    8.0,
    121.0,
    anchor="nw",
    text="Enter your email to reset your password",
    fill="#000000",
    font=("Staatliches Regular", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
