import os
import shutil
import subprocess
import sys
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog, messagebox

from DatabaseFunctions import User, AddUser, UserExist
from log_management import writing_in_log

path_1 = os.path.dirname(__file__) + r"\assets\frame0"
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(path_1)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def submit():
    global selected_image_path
    email = entry_2.get()
    name = entry_3.get()
    password = entry_1.get()



    try:
        if selected_image_path:
            if not UserExist(email):


                image_path = selected_image_path  # משתמשים בנתיב השמור
                image_base_name = os.path.basename(image_path)
                AddUser(email=email, password=password, name=name, profile_picture=image_base_name)
                messagebox.showinfo("User added successfully ","User added successfully " )
                next_page_path = os.path.dirname(__file__)
                next_page_path = next_page_path.split('gui')[0]
                next_page_path = next_page_path + r"gui\sign in\build\SignIn.py"
                print(next_page_path)
                subprocess.Popen([sys.executable, next_page_path])
            else:
                messagebox.showerror("Error", "User already exist")
    except NameError :
        messagebox.showerror("Error", "Upload a profile picture")




def uploadImage():
    global selected_image_path
    project_folder = os.path.join(os.getcwd())
    project_folder = project_folder.split('gui')[0]
    project_folder = project_folder + "images"

    if not os.path.exists(project_folder):
        os.makedirs(project_folder)


    file_path = filedialog.askopenfilename(filetypes=[("Image Files", "*.png;*.jpg;*.jpeg;*.gif")])

    if file_path:
        file_name = os.path.basename(file_path)
        destination_path = os.path.join(project_folder, file_name)
        shutil.copy(file_path, destination_path)
        selected_image_path = destination_path  # שמירת הנתיב שנבחר
        writing_in_log(f"image saved to: {destination_path}")
        print(f"File saved to: {destination_path}")
    else:
        print("No file selected.")


window = Tk()

window.geometry("413x392")
window.configure(bg = "#002849")


canvas = Canvas(
    window,
    bg = "#002849",
    height = 392,
    width = 413,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    60.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: submit(),
    relief="flat"
)
button_1.place(
    x=9.0,
    y=360.0,
    width=379.93695068359375,
    height=26.0
)

canvas.create_rectangle(
    4.0,
    157.0,
    398.0,
    158.0000343571512,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    9.0,
    272.0,
    37.0,
    304.0,
    fill="#235786",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    209.5,
    288.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=37.0,
    y=272.0,
    width=345.0,
    height=30.0
)

canvas.create_text(
    9.0,
    258.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Staatliches Regular", 12 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    23.0,
    288.0,
    image=image_image_2
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=354.0,
    y=279.0,
    width=23.0,
    height=19.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    209.5,
    193.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=37.0,
    y=177.0,
    width=345.0,
    height=30.0
)

canvas.create_rectangle(
    9.0,
    177.0,
    37.0,
    209.0,
    fill="#235786",
    outline="")

canvas.create_text(
    9.0,
    163.0,
    anchor="nw",
    text="Email",
    fill="#FFFDFD",
    font=("Staatliches Regular", 12 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    23.0,
    193.0,
    image=image_image_3
)

canvas.create_text(
    8.0,
    121.0,
    anchor="nw",
    text="enter details below to sign up ",
    fill="#000000",
    font=("Staatliches Regular", 24 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    209.5,
    239.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#0D397A",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=37.0,
    y=223.0,
    width=345.0,
    height=30.0
)

canvas.create_rectangle(
    9.0,
    223.0,
    37.0,
    255.0,
    fill="#235786",
    outline="")

canvas.create_text(
    9.0,
    209.0,
    anchor="nw",
    text="Name",
    fill="#FFFDFD",
    font=("Staatliches Regular", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    23.0,
    239.0,
    image=image_image_4
)

canvas.create_text(
    9.0,
    307.0,
    anchor="nw",
    text="profile image",
    fill="#FFFDFD",
    font=("Staatliches Regular", 12 * -1)
)

canvas.create_rectangle(
    9.0,
    321.0,
    37.0,
    353.0,
    fill="#235786",
    outline="")

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: uploadImage(),
    relief="flat"
)
button_3.place(
    x=14.0,
    y=328.0,
    width=18.0,
    height=18.0
)
window.resizable(False, False)
window.mainloop()